#!/bin/bash
## Script for PI cluster symmetry:
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=10
#SBATCH --cpus-per-task=4
#SBATCH --time=24:00:00
#SBATCH --output=./out/slurm-%j.out

python3 ./out/script0.py >> ./out/output.txt &
python3 ./out/script1.py >> ./out/output1.txt &
python3 ./out/script2.py >> ./out/output2.txt &
python3 ./out/script3.py >> ./out/output3.txt &
python3 ./out/script4.py >> ./out/output4.txt &
python3 ./out/script5.py >> ./out/output5.txt &
python3 ./out/script6.py >> ./out/output6.txt &
python3 ./out/script7.py >> ./out/output7.txt &
python3 ./out/script8.py >> ./out/output8.txt &
python3 ./out/script9.py >> ./out/output9.txt &
wait
